# syntax=docker/dockerfile:1.7
FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

COPY package.json package-lock.json* ./
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm ci

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
